# Generated by Django 4.2.16 on 2024-12-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_remove_calculator_action_calculator_hint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='value_2',
            field=models.FloatField(help_text='0 bulishi mumkin emas', null=True, verbose_name='2chi qiymat'),
        ),
    ]
