# Generated by Django 4.2.16 on 2024-12-06 18:04

import calculator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_calculator_value_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.CharField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='calculator',
            name='value_2',
            field=models.FloatField(help_text='0 bulishi mumkin emas', null=True, validators=[calculator.models.validate_zero], verbose_name='2chi qiymat'),
        ),
    ]
